name: SimpleCore
version: '${project.version}'
main: de.ruben.simplecore.SimpleCore
commands:
  weather:
    aliases: ["wetter"]
    permission: simplecore.weather
  workbench:
    aliases: ["wb"]
    permission: simplecore.workbench
  broadcast:
    aliases: ["bc", "benachrichtigung", "announcement", "announce"]
    permission: simplecore.broadcast
  rename:
    aliases: ["itemrename"]
    permission: simplecore.itemrename
  msg:
    aliases: ["pm", "nachricht", "message", "dm"]
    permission: simplecore.message
  r:
    aliases: ["reply", "antworten", "antwort"]
    permission: simplecore.reply
  enchant:
    aliases: ["verzaubern", "zauber", "enc"]
    permission: simplecore.enchant
  anvil:
    aliases: ["amboss"]
    permission: simplecore.anvil
  gamemode:
    aliases: ["gm", "spielmodus"]
    permission: simplecore.gamemode
  heal:
    aliases: ["heilen"]
    permission: simplecore.heal
  feed:
    aliases: ["food", "essen", "eat"]
    permission: simplecore.feed
  chatclear:
    permission: simplecore.chatclear
    aliases: ["cc"]
  lore:
    permission: simplecore.lore
    aliases: ["itemlore", "itembeschreibung"]
  teleport:
    aliases: ["tp"]
    permission: simplecore.teleport
  tpo:
    aliases: ["to"]
    permission: simplecore.tpo
  kill:
    permission: simplecore.kill
  nearby:
    permission: simplecore.nearby
    aliases: ["near"]
  day:
    permission: simplecore.time
  night:
    permission: simplecore.time
  midnight:
    permission: simplecore.time
  noon:
    permission: simplecore.time
  time:
    permission: simplecore.time
  invclear:
    permission: simplecore.invclear
    aliases: [ "clear" ]
  enderchest:
    permission: simplecore.enderchest
    aliases: ["ec"]
  repair:
    permission: simplecore.repair
    aliases: ["fix", "reparieren"]
