name: SimpleCore
version: '${project.version}'
main: de.ruben.simplecore.SimpleCore
commands:
  weather:
    aliases: ["wetter"]
    permission: simplecore.weather
  workbench:
    aliases: ["wb"]
    permission: simplecore.workbench
  broadcast:
    aliases: ["bc", "benachrichtigung", "announcement", "announce"]
    permission: simplecore.broadcast
